# Laboratorium 3 — NumPy
**Autor:** Dominika Wrześniewska

In [1]:
import numpy as np

# 1. Z listy

In [2]:
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


# 2. Zera — 10 elementów

In [3]:
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 3. Jedynki — macierz 3×5

In [4]:
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 4. Sekwencja od 0 do 100, co 10

In [6]:
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


# 5. 7 równomiernych punktów od 0 do 1

In [7]:
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


# 6. 20 losowych ocen od 2 do 5

In [8]:
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [9]:
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [16]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])


1. Sprzedaż w styczniu (indeks 0):

In [17]:
miesiace_sprzedaz[0]

np.int64(120)

2. Sprzedaż w grudniu (ostatni element):

In [18]:
miesiace_sprzedaz[-1]

np.int64(221)

3. Sprzedaż w Q1 (styczeń-marzec, indeksy 0-2)

In [19]:
miesiace_sprzedaz[0:3]

array([120, 135,  98])

4. Sprzedaż w Q4 (październik-grudzień, ostatnie 3):

In [21]:
miesiace_sprzedaz[-3:]

array([143, 198, 221])

5. Sprzedaż co drugi miesiąc (styczeń, marzec, maj…):

In [25]:
miesiace_sprzedaz[::2]

array([120,  98, 167, 201, 156, 198])

6. Sprzedaż od tyłu (grudzień → styczeń):

In [24]:
miesiace_sprzedaz[::-1]

array([221, 198, 143, 156, 178, 201, 189, 167, 142,  98, 135, 120])

Część B — Macierz 2D

In [27]:
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95],
# Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D 
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

1. Sprzedaż Produktu A w Q2 (wiersz 0, kolumna 1):

In [29]:
dane[0,1]

np.int64(145)

2. Cała sprzedaż Produktu C (wiersz 2, wszystkie kolumny):

In [30]:
dane[2]

array([234, 267, 289])

3. Sprzedaż wszystkich produktów w Q1 (wszystkie wiersze, kolumna 0):

In [36]:
dane[:,0]

array([120,  89, 234,  56])

4. Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2):

In [35]:
dane[1:3,1:3]

array([[102,  95],
       [267, 289]])

Ćwiczenie 3: Operacje wektorowe — analiza biznesowa (25
min)

In [37]:
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

Zadanie 1: Podstawowe statystyki cenowe

In [48]:
print("Średnia cena: " + str(ceny.mean()))
print("Najtańszy produkt: " + str(ceny.min()))
print("Najdroższy produkt: " + str(ceny.max()))

Średnia cena: 1171.0
Najtańszy produkt: 89
Najdroższy produkt: 3499


Zadanie 2: Wartość magazynu

In [52]:
wartosc_produkt = ceny * ilosci_magazyn

lacznie_magazyn = sum(wartosc_produkt)

print("Wartości produktów: " + str(wartosc_produkt))
print("Łączna wartość magazynu: " + str(lacznie_magazyn))

Wartości produktów: [ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
Łączna wartość magazynu: 549465


Zadanie 3: Analiza cenowa
# Stworz array z cenami po rabacie 15% (promocja świąteczna)
# Stworz array z cenami po uwzględnieniu VAT 23%
# Ile produktów kosztuje powyżej 1000 zł?
# Podpowiedź: rabat = ceny * 0.85, VAT = ceny * 1.23, zliczanie: (warunek).sum()

In [54]:
rabat = ceny * 0.85

vat = ceny * 1.23

pow_1000 = sum(ceny > 1000)

print("Ceny po rabacie :" + str(rabat))

print("Ceny z vat: " + str(vat))

print("Ilość produktów powyżej 1000zł: " + str(pow_1000))

Ceny po rabacie :[2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
Ceny z vat: [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
Ilość produktów powyżej 1000zł: 4


Zadanie 4: Filtrowanie
# Produkty z oceną >= 4.5 — nazwy i ceny
# Produkty poniżej 200 zł — nazwy i ilości w magazynie
# Podpowiedź: maska = oceny_klientow >= 4.5, potem ceny[maska]
# Uwaga: nazwy to zwykła lista — zamień ją na np.array(nazwy), żeby użyć maski

In [58]:
nazwy_a = np.array(nazwy)
maska = (oceny_klientow >= 4.5)
wys_ocena = nazwy_a[maska]
ceny_ocena = ceny[maska]
print("Produkty z wysoką oceną: " + str(wys_ocena))
print("Ich ceny: " + str(ceny_ocena))

maska_pon = (ceny < 200)
nazwy_pon = nazwy_a[maska_pon]
ilosci_pon = ilosci_magazyn[maska_pon]
print("Produkty poniżej 200zł: " + str(nazwy_pon))
print("Ilości: " + str(ilosci_pon))

Produkty z wysoką oceną: ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor']
Ich ceny: [3499 2499  349 1499]
Produkty poniżej 200zł: ['Ładowarka' 'Mysz']
Ilości: [312 201]


Zadanie 5: Analiza zapasów
# Produkty z niskim stanem magazynowym (< 30 szt.) — nazwy
# Łączna wartość tych produktów
# Ile % całego magazynu stanowią?
# Podpowiedź: wartosci = ceny * ilosci_magazyn, potem filtruj maską

In [67]:
maska_mal = (ilosci_magazyn < 30)
produkty_mal = nazwy_a[maska_mal]
print("Produkty z niskim stanem magazynowym: " + str(produkty_mal))

wart_mag = (ceny * ilosci_magazyn)
wart_mal = sum(wart_mag[maska_mal])
print("Wartość produktów z niskim stanem magazynowym: " + str(wart_mal) + "zł.")

suma_mal = sum(ilosci_magazyn[maska_mal])
sum_wszystkich = sum(ilosci_magazyn)

procent = (suma_mal / sum_wszystkich) * 100
print("Stanowią " + str(round(procent)) + "%.")

Produkty z niskim stanem magazynowym: ['Laptop' 'Monitor']
Wartość produktów z niskim stanem magazynowym: 86962zł.
Stanowią 4%.


Zadanie 6 (bonus): Analiza korelacji cena–ocena
# Które produkty są "okazją" — ocena >= 4.5 i cena < 1000 zł? Wypisz nazwy i ceny.
# Jaka jest średnia cena produktów z oceną >= 4.0 vs < 4.0?
# Podpowiedź: łączenie warunków: (warunek1) & (warunek2)

In [71]:
maska_okazja = (oceny_klientow >= 4.5) & (ceny < 1000)
prod_okazje = nazwy_a[maska_okazja]
ceny_okazja = ceny[maska_okazja]
print("Produkty które są okazją: " + str(prod_okazje))
print("Ceny: " + str(ceny_okazja))

maska_wysokie = (oceny_klientow >= 4.0)
maska_niskie = (oceny_klientow < 4.0)
srednia_wysokie = np.mean(ceny[maska_wysokie])
srednia_niskie = np.mean(ceny[maska_niskie])
print("Średnia cena produktów z niską oceną: " + str(round(srednia_niskie)))
print("Średnia cena produktów z wysoką oceną: " + str(round(srednia_wysokie)))

Produkty które są okazją: ['Słuchawki']
Ceny: [349]
Średnia cena produktów z niską oceną: 529
Średnia cena produktów z wysoką oceną: 1446


Sprawdzenie ￿
Kluczowe odpowiedzi:- Średnia cena: 1171.0 zł- Najdroższy: Laptop (3499
zł), najtańszy: Ładowarka (89 zł)- Wartość magazynu: 549 465 zł- Pro
dukty z oceną ￿ 4.5: Laptop, Smartfon, Słuchawki, Monitor- Produkty < 30
szt.: Laptop (15), Monitor (23)- Bonus — „okazje” (ocena ￿ 4.5 i cena <
1000): Słuchawki (349 zł, ocena 4.8)- Bonus — średnia cena przy ocenie ￿ 4.0:
1446.14 zł, przy < 4.0: 529.00 zł

Ćwiczenie 4: Benchmark — lista vs NumPy (15 min)
Cel
Przekonaj się na własne oczy, jak szybki jest NumPy w porównaniu z listami.

In [72]:
import time

In [73]:
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [74]:
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter()- start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 81.4 ms
NumPy: 5.2 ms
NumPy jest 16× szybszy!


In [75]:
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter()- start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter()- start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 8.3 ms
NumPy: 1.2 ms
NumPy jest 7× szybszy!


In [76]:
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter()- start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 43.8 ms
NumPy: 4.3 ms
NumPy jest 10× szybszy!


## Wnioski z benchmarku- NumPy jest **16×** szybszy w mnożeniu
- NumPy jest **7×** szybszy w sumowaniu- 
NumPy jest **10×** szybszy w filtrowaniu- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list